[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "6V7KDobc2YZaFbQPfmEG3oymuLF9KYN1rCpUHYgAgNnK"

[programs.devnet]
solana_twitter = "6V7KDobc2YZaFbQPfmEG3oymuLF9KYN1rCpUHYgAgNnK"

[programs.mainnet]
solana_twitter = "6V7KDobc2YZaFbQPfmEG3oymuLF9KYN1rCpUHYgAgNnK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
